FROM nvidia/cuda:12.4.1-runtime-rockylinux9 

# https://gitlab.com/nvidia/container-images/cuda.git
# ~/cuda/dist/12.4.1/rockylinux9/devel/Dockerfile

ENV NV_CUDA_LIB_VERSION 12.4.1-1
ENV NV_CUDA_CUDART_DEV_VERSION 12.4.127-1

RUN dnf install -y \
    make \
    findutils \
    cuda-command-line-tools-12-4-${NV_CUDA_LIB_VERSION} \
    cuda-libraries-devel-12-4-${NV_CUDA_LIB_VERSION} \
    cuda-minimal-build-12-4-${NV_CUDA_LIB_VERSION} \
    cuda-cudart-devel-12-4-${NV_CUDA_CUDART_DEV_VERSION} \
    && dnf clean all \
    && rm -rf /var/cache/yum/*

#    ${NV_NVPROF_DEV_PACKAGE} \
#    cuda-nvml-devel-12-4-${NV_NVML_DEV_VERSION} \
#    libcublas-devel-12-4-${NV_LIBCUBLAS_DEV_VERSION} \
#    ${NV_LIBNPP_DEV_PACKAGE} \
#    ${NV_LIBNCCL_DEV_PACKAGE} \
#    ${NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE} \




ARG TARGETARCH
ARG TARGETOS
ARG TARGETPLATFORM

ARG BUILDARCH
ARG BUILDOS
ARG BUILDPLATFORM

RUN echo "TARGETPLATFORM $TARGETPLATFORM"
RUN echo "TARGETOS       $TARGETOS"
RUN echo "TARGETARCH     $TARGETARCH"

RUN echo "BUILDPLATFORM  $BUILDPLATFORM"
RUN echo "BUILDOS        $BUILDOS"
RUN echo "BUILDARCH      $BUILDARCH"


ARG PASSWORD

RUN useradd juno
RUN usermod -G wheel -a juno
RUN echo -n "assumeyes=1" >> /etc/yum.conf

RUN dnf install 'dnf-command(config-manager)'
RUN dnf config-manager --set-enabled crb

RUN dnf install -y epel-release
RUN dnf install -y rocky-repos   # looks equivalent to almalinux-release-devel
RUN dnf install -y sudo 
#RUN dnf install -y redhat-lsb-core  # skipped as not easily available for rockylinux9   
RUN dnf install -y wget 
RUN dnf install -y subversion
RUN dnf install -y git 
RUN dnf install -y make 
RUN dnf install -y gcc-c++ 
RUN dnf install -y gcc 
RUN dnf install -y binutils
RUN dnf install -y libX11-devel 
RUN dnf install -y libXpm-devel 
RUN dnf install -y libXft-devel 
RUN dnf install -y libXext-devel
RUN dnf install -y gcc-gfortran
RUN dnf install -y openssl-devel
RUN dnf install -y pcre-devel 
RUN dnf install -y mesa-libGL-devel
RUN dnf install -y glew-devel
RUN dnf install -y ftgl-devel
RUN dnf install -y mysql-devel
RUN dnf install -y fftw-devel 
RUN dnf install -y cfitsio-devel 
RUN dnf install -y graphviz-devel
RUN dnf install -y avahi-compat-libdns_sd-devel
RUN dnf install -y python3-devel
RUN dnf install -y libxml2-devel 
RUN dnf install -y gsl-devel
RUN dnf install -y qt5-devel 
RUN dnf install -y bzip2-devel 
RUN dnf install -y imake 
RUN dnf install -y patch 
RUN dnf install -y ncurses-devel 
RUN dnf install -y readline-devel
RUN dnf install -y sqlite-devel 
RUN dnf install -y tk-devel 
RUN dnf install -y openldap-devel
RUN dnf install -y motif 
RUN dnf install -y motif-devel 
RUN dnf install -y openmotif 
RUN dnf install -y openmotif-devel
RUN dnf install -y wget 
RUN dnf install -y libcurl-devel 
RUN dnf install -y unzip
RUN dnf install -y bzip2
RUN dnf install -y libicu-devel
RUN dnf install -y libglvnd-devel 
RUN dnf install -y libXmu-devel 

RUN echo 'juno ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

RUN sudo dnf install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm \
  && sudo dnf install -y cvmfs \
  && sudo mkdir /etc/cvmfs/keys/ihep.ac.cn \
  && sudo curl -o /etc/cvmfs/keys/ihep.ac.cn/ihep.ac.cn.pub http://cvmfs-stratum-one.ihep.ac.cn/cvmfs/software/client_configure/ihep.ac.cn/ihep.ac.cn.pub \
  && sudo curl -o /etc/cvmfs/domain.d/ihep.ac.cn.conf http://cvmfs-stratum-one.ihep.ac.cn/cvmfs/software/client_configure/ihep.ac.cn.conf \
  && echo "CVMFS_REPOSITORIES='sft.cern.ch,juno.ihep.ac.cn,container.ihep.ac.cn'" | sudo tee    /etc/cvmfs/default.local \
  && echo "CVMFS_HTTP_PROXY=DIRECT"                                                 | sudo tee -a /etc/cvmfs/default.local \
  && cat /etc/cvmfs/default.local \
  && sudo mkdir -p /cvmfs/sft.cern.ch \
  && sudo mkdir -p /cvmfs/juno.ihep.ac.cn \
  && sudo mkdir -p /cvmfs/container.ihep.ac.cn;

RUN sudo dnf install -y expat-devel
RUN sudo dnf install -y libtool
RUN sudo dnf install -y libuuid-devel
RUN sudo dnf install -y libnsl2-devel
RUN sudo dnf install -y rsync

USER juno
WORKDIR /home/juno

