
name: pull-docker-image-and-inspect-and-scp 
on: [push]

jobs:
  job0-pull-docker-image-and-inspect-and-scp: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Adding Known Hosts
        run: |
           echo "ssh-keyscan" 
           mkdir ~/.ssh 
           ssh-keyscan -H ${{ secrets.SANDBOX_DEPLOY_HOST }} >> ~/.ssh/known_hosts
           cat ~/.ssh/known_hosts 

      - name: Plant key and start agent  
        env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
           echo "Plant key and start agent " 
           echo "${{ secrets.SANDBOX_DEPLOY_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
           ssh-add ~/.ssh/id_rsa    


      - name: docker-pull-inspect-save-scp   
        env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
           echo "[ Pull docker image and scp "
           pwd
           echo github.workspace ${{ github.workspace }}

           #image=nvidia/cuda:12.4.1-devel-rockylinux9@sha256-483ac85033dfcf05066887e530fbb18b9f0abac2a84545900ef53733559fb20e
           #gives invalid reference format
           #image=nvidia/cuda:12.4.1-devel-rockylinux9
           #name=cuda12-4-1-devel-rl9-amd

           ref=junosw/base:el9
           nam=junosw_base_el9
           out=/tmp/$nam.tar

           echo "[ docker pull $ref" 
           date 
           docker pull --platform linux/amd64 $ref 
           date 
           echo "] docker pull $ref" 
    
           echo "[ docker image ls" 
           date 
           docker image ls
           date 
           echo "] docker image ls" 

           echo "[ docker manifest inspect -v $ref"
           date 
           docker manifest inspect -v $ref
           date 
           echo "] docker manifest inspect -v $ref"


           echo "[ docker buildx imagetools inspect $ref"
           date 
           docker buildx imagetools inspect $ref
           date 
           echo "] docker buildx imagetools inspect $ref"

           echo "[ save ref $ref out $out"
           date 
           docker save $ref > $out
           date 
           echo "] save ref $ref out $out"

           echo "[ du/tar-tvf/ls out $out  "
           du -h $out
           tar tvf $out
           ls -alst $out
           echo "] du/tar tvf/ls  "
 

           echo "[scp.0 out $out " 
           date 
           scp $out ${{ secrets.SANDBOX_DEPLOY_USER }}@${{ secrets.SANDBOX_DEPLOY_HOST }}:${{ secrets.SANDBOX_DEPLOY_FOLD }}
           date 
           echo "]scp.0" 
           echo "] Build docker image and scp "



