
name: pull-docker-image-and-inspect 
on: [push]

jobs:
  job0-pull-docker-image-and-scp: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Adding Known Hosts
        run: |
           echo "ssh-keyscan" 
           mkdir ~/.ssh 
           ssh-keyscan -H ${{ secrets.SANDBOX_DEPLOY_HOST }} >> ~/.ssh/known_hosts
           cat ~/.ssh/known_hosts 

      - name: Plant key and start agent  
        env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
           echo "Plant key and start agent " 
           echo "${{ secrets.SANDBOX_DEPLOY_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
           ssh-add ~/.ssh/id_rsa    


      - name: Pull docker image and inspect  
        env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
           echo "[ Pull docker image and scp "
           pwd
           echo github.workspace ${{ github.workspace }}
           ls -alst ${{ github.workspace }}/bb/Dockerfile 

           #image=nvidia/cuda:12.4.1-devel-rockylinux9@sha256-483ac85033dfcf05066887e530fbb18b9f0abac2a84545900ef53733559fb20e
           #gives invalid reference format
           image=nvidia/cuda:12.4.1-devel-rockylinux9
           name=cuda12-4-1-devel-rl9-amd

           echo "docker pull $image" 
           docker pull --platform linux/amd64 $image 
           docker image ls
           docker manifest inspect -v $image
           docker buildx imagetools inspect $image



