name: simoncblyth-pull-docker-image-and-scp 
on: [push]

env:
  NAM: simoncblyth
  TAG: cuda:12.4.1-runtimeplus-rockylinux9
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  LIVE: 0 


jobs:
  docker: 
    runs-on: ubuntu-latest 
    steps:
      - name: GitHub Checkout 
        uses: actions/checkout@v4

      - name: Prep known_hosts 
        run: |
           mkdir ~/.ssh 
           ssh-keyscan -H ${{ secrets.SANDBOX_DEPLOY_HOST }} >> ~/.ssh/known_hosts
           cat ~/.ssh/known_hosts 

      - name: Plant key and start agent  
        run: |
           echo "${{ secrets.SANDBOX_DEPLOY_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
           ssh-add ~/.ssh/id_rsa    

      - name: docker pull 
        if: ${{ env.LIVE }} == 1
        run: |
           pwd
           echo "[ docker pull [$NAM/$TAG] "
           date
           docker pull --platform linux/amd64 $NAM/$TAG 
           date
           echo "] docker pull [$NAM/$TAG] "

      - name: set TAR
        run: |

           tag=$TAG
           tag=${tag//:/_}
           tag=${tag//./_}
           tag=${tag//-/_}

           echo "TAR=${NAM}_${tag}" >> "$GITHUB_ENV"  
 
        shell: bash

      - name: check TAR
        run: |
           echo "TAR [$TAR]" 


      - name: docker images  
        if: ${{ env.LIVE }} == 1
        run: |
           docker images

      - name: docker manifest inspect 
        if: ${{ env.LIVE }} == 1
        run: |
           docker manifest inspect -v $NAM/$TAG

      - name: docker buildx imagetools inspect 
        if: ${{ env.LIVE }} == 1
        run: |
           docker buildx imagetools inspect $NAM/$TAG

      - name: docker save 
        if: ${{ env.LIVE }} == 1
        run: |
           docker save $NAM/$TAG > $TAR

      - name: du/tar/ls 
        if: ${{ env.LIVE }} == 1
        run: |
           du -h $TAR
           tar tvf $TAR
           ls -alst $TAR

      - name: scp 
        if: ${{ env.LIVE }} == 1
        run: |
           date 
           scp $TAR ${{ secrets.SANDBOX_DEPLOY_USER }}@${{ secrets.SANDBOX_DEPLOY_HOST }}:${{ secrets.SANDBOX_DEPLOY_FOLD }}
           date 




