name: simoncblyth-build-docker-image-and-push  
on: [push]

jobs:
  docker: 
    runs-on: ubuntu-latest 
    steps:
      - name: GitHub Checkout 
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SANDBOX_DOCKERHUB_USER }}
          password: ${{ secrets.SANDBOX_DOCKERHUB_SCB0 }}


      - name: Build docker image and push 
        run: |
           echo "[ Build docker image and push "
           pwd

           #recipe=base
           #recipe=runtime
           recipe=runtimeplus
           #recipe=devel

           dok=junosw/Dockerfile-junosw-cuda-${recipe}-el9
           tag=simoncblyth/cuda:12.4.1-${recipe}-rockylinux9

           echo recipe $recipe
           echo dok $dok
           echo tag $tag

           echo "[ build "
           date
           docker build --tag $tag --platform linux/amd64 - < $dok
           date
           echo "] build "

           #echo "[ df -h "
           #df -h
           #echo "] df -h "
           
           echo "[ image ls "
           date
           docker image ls
           date
           echo "] image ls "


