name: simoncblyth-build-docker-image-and-push  
on: [push]

env:
  DOK: junosw/Dockerfile-junosw-cuda-runtimeplus-el9
  TAG: ${{ secrets.SANDBOX_DOCKERHUB_USER }}/cuda:12.4.1-runtimeplus-rockylinux9

jobs:
  docker: 
    runs-on: ubuntu-latest 
    env:
       URL:https://github.com/${{ github.repository }}/blob/master/${{ env.DOK  }}

    steps:
      - name: GitHub Checkout 
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SANDBOX_DOCKERHUB_USER }}
          password: ${{ secrets.SANDBOX_DOCKERHUB_SCB0 }}

      - name: build  
        run: |
           pwd
           echo "[ build TAG [$TAG] DOK [$DOK] URL [$URL]"
           date
           #docker build --tag $TAG --label "src=$URL" --platform linux/amd64 - < $DOK
           date
           echo "] build TAG [$TAG] DOK [$DOK] URL [$URL]"

      - name: images  
        run: |
           pwd
           docker images

      - name: push
        run: |
           pwd
           echo "[ push TAG [$TAG] "
           date
           #docker push $TAG 
           date
           echo "] push TAG [$TAG] "





