name: simoncblyth-build-docker-image-and-push  
on: [push]

env:
  DOK: junosw/Dockerfile-junosw-cuda-runtimeplus-el9
  NAM: simoncblyth
  TAG: cuda:12.4.1-runtimeplus-rockylinux9

jobs:
  docker: 
    runs-on: ubuntu-latest 
    steps:
      - name: GitHub Checkout 
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3
        with:
          username: ${{ env.NAM }}
          password: ${{ secrets.SANDBOX_DOCKERHUB_SCB0 }}

      - name: build  
        env:
           SRC: https://github.com/${{ github.repository }}/blob/master/${{ env.DOK  }}

        run: |
           pwd
           echo "[ build --tag [$NAM/$TAG] DOK [$DOK] SRC [$SRC]"
           date
           docker build --tag $NAM/$TAG --label "src=$SRC" --platform linux/amd64 - < $DOK
           date
           echo "] build --tag [$NAM/$TAG] DOK [$DOK] SRC [$SRC]"

      - name: images  
        run: |
           pwd
           docker images

      - name: push
        run: |
           pwd
           echo "[ push NAM/TAG [$NAM/$TAG] "
           date
           docker push $NAM/$TAG 
           date
           echo "] push NAM/TAG [$NAM/$TAG] "





