# https://www.nutrient.io/blog/docker-import-export-vs-load-save/

name: try-docker-build

on: [push]

jobs:
  check-docker-build: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Within VM
        run: |
           echo "Running VM "
           pwd
           echo $PATH
           which docker
           docker --version
           ls -alst
           date
           ls -alst bb
           ls -alst bb/Dockerfile 

           echo github.workspace ${{ github.workspace }}
           echo GITHUB_WORKSPACE $GITHUB_WORKSPACE  

           ls -alst ${{ github.workspace }}/bb/Dockerfile 
           ls -alst $GITHUB_WORKSPACE/bb/Dockerfile 

           cd bb 
           docker build --tag bb42 .
           docker image ls
           docker run bb42
           docker save bb42 > bb42.tar
           tar tvf bb42.tar

           ls -alst .  


