
name: try-ssh-commands
on: [push]

jobs:
  check-ssh-commands: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Adding Known Hosts
        run: |
           echo "ssh-keyscan" 
           mkdir ~/.ssh 
           ssh-keyscan -H ${{ secrets.SANDBOX_DEPLOY_HOST }} >> ~/.ssh/known_hosts
           cat ~/.ssh/known_hosts 

      - name: Plant key and start agent  
        env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
           echo "Plant key and start agent " 
           echo "${{ secrets.SANDBOX_DEPLOY_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
           ssh-add ~/.ssh/id_rsa    


      - name: Within VM
        env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock

        run: |
           echo "Running VM "
           pwd
           echo $PATH
           which docker
           docker --version
           ls -alst
           date
           ls -alst bb
           ls -alst bb/Dockerfile 

           echo github.workspace ${{ github.workspace }}
           echo GITHUB_WORKSPACE $GITHUB_WORKSPACE  


           ls -alst ${{ github.workspace }}/bb/Dockerfile 
           ls -alst $GITHUB_WORKSPACE/bb/Dockerfile 

           echo hello from GHA VM SANDBOX_DEPLOY_LAST ${{ secrets.SANDBOX_DEPLOY_LAST }}  > /tmp/hello.txt
           date >> /tmp/hello.txt
           date >> /tmp/hello.txt
           cat /tmp/hello.txt

           scp /tmp/hello.txt ${{ secrets.SANDBOX_DEPLOY_USER }}@${{ secrets.SANDBOX_DEPLOY_HOST }}:${{ secrets.SANDBOX_DEPLOY_FOLD }}


