
name: try-ssh-commands
on: [push]

jobs:
  check-ssh-commands: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
  
      - name: Adding Known Hosts
         run: |
           echo "ssh-keyscan" 
           ls ~/.ssh 
           ssh-keyscan -H ${{ secrets.SANDBOX_DEPLOY_HOST }} >> ~/.ssh/known_hosts
           cat ~/.ssh/known_hosts 


     - name: Within VM
        run: |
           echo "Running VM "
           pwd
           echo $PATH
           which docker
           docker --version
           ls -alst
           date
           ls -alst bb
           ls -alst bb/Dockerfile 

           echo github.workspace ${{ github.workspace }}
           echo GITHUB_WORKSPACE $GITHUB_WORKSPACE  


           ls -alst ${{ github.workspace }}/bb/Dockerfile 
           ls -alst $GITHUB_WORKSPACE/bb/Dockerfile 

           which which
           which ssh-keyscan
           which ssh-agent
           which ssh-add         

