# https://www.nutrient.io/blog/docker-import-export-vs-load-save/

name: try-docker-build

on: [push]

jobs:
  check-docker-build: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Within VM
        run: |
           echo "Running VM "
           pwd
           echo $PATH
           which docker
           docker --version
           ls -alst
           date
           docker build --tag bb42 bb/bb42-Dockerfile
           docker image ls
           docker run bb42
           docker save bb42 > bb42.tar
           tar tvf bb42.tar

