#

name: try-docker-container
on: [push]

jobs:
  check-docker-run-action: 
    runs-on: ubuntu-latest 
    container:
      image: busybox
      run: |
         echo "Running Script in busybox "
         pwd


